### PR TITLE
Fix manifest validation.

### LINKED ISSUE #53: New Node Catch-up
Make sure that a newly added node can catch up with the other nodes.

### PR DESCRIPTION
**Pull request by mattcollier**
Fixes #53.

### CODE REVIEW

File: lib/election.js [hunk 1]
```diff
@@ -855,6 +883,10 @@ function _getManifestFromPeer(
         return _validateEvents(
           ledgerNode, manifest.item, manifest.blockHeight, callback);
       }
+
+      // FIXME: bypassing this check, votes are in the process of being saved
```
Comment (mattcollier) [inline lib/election.js]: @dlongley I'd like to get this PR merged, and then create another issue for re-implementing the vote check here.
